version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      codemirror:
        patterns:
          - "@codemirror/*"
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      codemirror:
        patterns:
          - "@codemirror/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
